import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Dashboard
    "dashboard.title": "Bonjour ! 👋",
    "dashboard.subtitle": "Voici un aperçu de votre situation financière aujourd'hui",
    "dashboard.revenu": "Revenus totaux",
    "dashboard.expenses": "Dépenses totales",
    "dashboard.income": "Revenu net",
    "dashboard.margin": "Marge bénéficiaire",
    "dashboard.revenuVsExpenses": "Revenus vs Dépenses",
    "dashboard.expenseCategories": "Catégories de dépenses",
    "dashboard.monthlyBreakdown": "Répartition mensuelle",
    "dashboard.recentTransactions": "Transactions récentes",
    "dashboard.viewAll": "Voir tout",
    "dashboard.vsLastPeriod": "vs période précédente",
    "dashboard.date": "Date",
    "dashboard.description": "Description",
    "dashboard.category": "Catégorie",
    "dashboard.type": "Type",
    "dashboard.amount": "Montant",
    "dashboard.incomeType": "Revenu",
    "dashboard.expenseType": "Dépense",
    "dashboard.periodThisMonth": "Ce mois",
    "dashboard.periodThisQuarter": "Ce trimestre",
    "dashboard.periodYearToDate": "Année en cours",
    "dashboard.periodAllTime": "Tout",
    "dashboard.moreFilters": "Plus de filtres",
    "dashboard.revenuLabel": "Revenus",
    "dashboard.expensesLabel": "Dépenses",
    
    // Dashboard - Months
    "dashboard.monthJan": "Jan",
    "dashboard.monthFeb": "Fév",
    "dashboard.monthMar": "Mar",
    "dashboard.monthApr": "Avr",
    "dashboard.monthMay": "Mai",
    "dashboard.monthJun": "Jun",
    "dashboard.monthJul": "Jul",
    "dashboard.monthAug": "Aoû",
    "dashboard.monthSep": "Sep",
    "dashboard.monthOct": "Oct",
    "dashboard.monthNov": "Nov",
    "dashboard.monthDec": "Déc",
    
    // Dashboard - Expense Categories
    "dashboard.categorySalaries": "Salaires",
    "dashboard.categoryOfficeSupplies": "Fournitures de bureau",
    "dashboard.categoryTravel": "Voyage",
    "dashboard.categoryEquipment": "Équipement",
    "dashboard.categoryOther": "Autre",
    
    // Dashboard - Transaction Categories
    "dashboard.transactionCategoryConsulting": "Conseil",
    "dashboard.transactionCategoryOfficeSupplies": "Fournitures de bureau",
    "dashboard.transactionCategoryMealsEntertainment": "Repas et divertissement",
    "dashboard.transactionCategorySoftware": "Logiciel",
    
    // Dashboard - Transaction Descriptions
    "dashboard.transactionClientInvoice": "Facture client",
    "dashboard.transactionOfficeSupplies": "Fournitures de bureau",
    "dashboard.transactionTeamLunch": "Déjeuner d'équipe",
    "dashboard.transactionSoftwareLicense": "Licence logicielle",
    "dashboard.transactionFreelancePayment": "Paiement freelance",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérez vos préférences de compte et d'application.",
    "settings.general": "Général",
    "settings.account": "Compte",
    "settings.notifications": "Notifications",
    "settings.billing": "Facturation",
    "settings.language": "Langue",
    "settings.languageDescription": "Choisissez la langue d'affichage de l'application",
    "settings.save": "Enregistrer les modifications",
    
    // Sidebar
    "sidebar.dashboard": "Tableau de bord",
    "sidebar.companies": "Entreprises",
    "sidebar.transactions": "Transactions",
    "sidebar.accounting": "Comptabilité",
    "sidebar.taxFiling": "Déclaration fiscale",
    "sidebar.reports": "Rapports",
    "sidebar.anomalies": "Anomalies",
    "sidebar.assets": "Actifs",
    "sidebar.settings": "Paramètres",
    "sidebar.brand": "NovaFinance",
    "sidebar.tagline": "Gestion Financière",
    "sidebar.footer": "© 2024 NovaFinance",
    "sidebar.footerTagline": "La finance simplifiée ✨",
    "sidebar.personalDashboard": "Tableau de bord",
    "sidebar.personalTransactions": "Transactions",
    "sidebar.personalBudget": "Budget",
    "sidebar.personalAccounts": "Comptes",
    "sidebar.personalCards": "Cartes",
    "sidebar.personalSavings": "Épargne",
    "sidebar.personalReports": "Rapports",
    "sidebar.personalSettings": "Paramètres",
    
    // Header
    "header.search": "Rechercher transactions, entreprises...",
    "header.user": "Utilisateur",
    "header.admin": "Admin",
    "header.logout": "Déconnexion",
    "header.logoutSuccess": "Déconnexion réussie",
    "header.logoutSuccessDesc": "Vous avez été déconnecté avec succès.",
    "header.logoutError": "Erreur",
    "header.logoutErrorDesc": "Une erreur est survenue lors de la déconnexion.",
    "header.modeBusiness": "Entreprise",
    "header.modePersonal": "Personnelle",
    "header.modeBusinessActive": "Mode entreprise actif",
    "header.modePersonalActive": "Mode finance personnelle actif",
    "header.selectFiscalYear": "Sélectionner l'année fiscale",
    "header.changeMode": "Changer de mode",
    "header.goToSettings": "Aller aux paramètres",
    
    // Settings - General
    "settings.generalSettings": "Paramètres généraux",
    "settings.defaultCurrency": "Devise par défaut",
    "settings.fiscalYearStart": "Début de l'année fiscale",
    "settings.theme": "Thème",
    "settings.themeLight": "Clair",
    "settings.themeDark": "Sombre",
    "settings.currencyCAD": "Dollar canadien (CAD)",
    "settings.currencyUSD": "Dollar américain (USD)",
    "settings.currencyEUR": "Euro (EUR)",
    "settings.monthJanuary": "Janvier",
    "settings.monthApril": "Avril",
    "settings.monthJuly": "Juillet",
    
    // Settings - Account
    "settings.accountSettings": "Paramètres du compte",
    "settings.profilePhoto": "Photo de profil",
    "settings.uploadPhoto": "Télécharger une photo",
    "settings.changePhoto": "Changer la photo",
    "settings.photoHint": "Formats acceptés: JPG, PNG, GIF. Taille max: 5MB",
    "settings.fullName": "Nom complet",
    "settings.email": "Email",
    "settings.phone": "Téléphone",
    "settings.updateAccount": "Mettre à jour le compte",
    
    // Settings - Notifications
    "settings.notificationPreferences": "Préférences de notification",
    "settings.taxDeadlineReminders": "Rappels d'échéances fiscales",
    "settings.taxDeadlineDesc": "Recevoir des notifications sur les échéances fiscales à venir",
    "settings.monthlyReports": "Rapports mensuels",
    "settings.monthlyReportsDesc": "Recevoir des résumés financiers mensuels",
    "settings.largeTransactions": "Transactions importantes",
    "settings.largeTransactionsDesc": "Notifier pour les transactions supérieures à 5 000 $",
    "settings.systemUpdates": "Mises à jour système",
    "settings.systemUpdatesDesc": "Recevoir des notifications sur les mises à jour de l'application",
    
    // Settings - Billing
    "settings.billingSubscription": "Facturation et abonnement",
    "settings.currentPlan": "Plan actuel",
    "settings.professional": "Professionnel",
    "settings.paymentMethod": "Méthode de paiement",
    "settings.edit": "Modifier",
    
    // Settings - Security
    "settings.security": "Sécurité",
    "settings.changePassword": "Changer le mot de passe",
    "settings.currentPassword": "Mot de passe actuel",
    "settings.newPassword": "Nouveau mot de passe",
    "settings.confirmPassword": "Confirmer le mot de passe",
    "settings.updatePassword": "Mettre à jour le mot de passe",
    "settings.twoFactorAuth": "Authentification à deux facteurs",
    "settings.twoFactorDesc": "Ajoutez une couche de sécurité supplémentaire à votre compte.",
    "settings.enable2FA": "Activer l'A2F",
    
    // NotFound
    "notFound.title": "Page introuvable",
    "notFound.message": "Désolé, nous n'avons pas pu trouver la page que vous recherchez. Retournons au tableau de bord.",
    "notFound.backToDashboard": "Retour au tableau de bord",
    
    // Companies
    "companies.title": "Entreprises",
    "companies.subtitle": "Gérez vos profils d'entreprise et informations fiscales.",
    "companies.addCompany": "Ajouter une entreprise",
    "companies.businessNumber": "Numéro d'entreprise",
    "companies.neq": "NEQ",
    "companies.taxNumber": "Numéro fiscal",
    "companies.owner": "Propriétaire",
    "companies.contactEmail": "Email de contact",
    "companies.integrations": "Intégrations",
    "companies.stripeConnected": "✓ Stripe Connecté",
    "companies.stripe": "Stripe",
    "companies.ytdrevenu": "Revenus",
    "companies.addNewCompany": "Ajouter une nouvelle entreprise",
    "companies.companyName": "Nom de l'entreprise",
    "companies.companyNamePlaceholder": "Entrez le nom de l'entreprise",
    "companies.legalName": "Nom légal",
    "companies.legalNamePlaceholder": "Entrez le nom légal de l'entreprise",
    "companies.businessNumberPlaceholder": "123-456-789",
    "companies.neqPlaceholder": "1234 5678 90",
    "companies.cancel": "Annuler",
    "companies.createCompany": "Créer l'entreprise",
    "companies.moreOptions": "Plus d'options",
    "companies.editCompany": "Modifier l'entreprise",
    "companies.deleteCompany": "Supprimer l'entreprise",
    
    // Transactions
    "transactions.title": "Dépenses et Revenus",
    "transactions.subtitle": "Suivez et gérez toutes vos transactions financières.",
    "transactions.addTransaction": "Ajouter une transaction",
    "transactions.totalIncome": "Revenus totaux",
    "transactions.totalExpenses": "Dépenses totales",
    "transactions.net": "Net",
    "transactions.searchPlaceholder": "Rechercher des transactions...",
    "transactions.allTransactions": "Toutes les transactions",
    "transactions.incomeOnly": "Revenus uniquement",
    "transactions.expensesOnly": "Dépenses uniquement",
    "transactions.export": "Exporter",
    "transactions.print": "Imprimer",
    "transactions.company": "Entreprise",
    "transactions.tags": "Tags",
    "transactions.actions": "Actions",
    "transactions.addTransactionTitle": "Ajouter une transaction",
    "transactions.type": "Type",
    "transactions.description": "Description",
    "transactions.descriptionPlaceholder": "Entrez la description",
    "transactions.amount": "Montant",
    "transactions.amountPlaceholder": "0.00",
    "transactions.category": "Catégorie",
    "transactions.date": "Date",
    "transactions.income": "Revenu",
    "transactions.expense": "Dépense",
    "transactions.addCustomCategory": "Ajouter une catégorie personnalisée",
    "transactions.customCategoryPlaceholder": "Nom de la catégorie",
    "transactions.categoryUtilities": "Services publics",
    "transactions.account": "Compte",
    "transactions.accountTo": "Compte de destination",
    "transactions.transferType": "Type de transfert",
    "transactions.transferBetweenAccounts": "Transfert entre comptes",
    "transactions.transferBetweenPersons": "Transfert entre personnes",
    "transactions.typerevenu": "Revenu",
    "transactions.typeDepense": "Dépense",
    "transactions.typeTransfert": "Transfert",
    "transactions.typeRemboursement": "Remboursement",
    "transactions.typePaiementFacture": "Paiement de facture",
    "transactions.allAccounts": "Tous les comptes",
    "transactions.allCompanies": "Toutes les entreprises",
    "transactions.allIncomeExpenses": "Tous (Revenus + Dépenses)",
    "transactions.filterByType": "Filtrer par type de transaction",
    "transactions.filterByDate": "Filtrer par date",
    "transactions.filterByAccount": "Filtrer par compte",
    "transactions.filterByCompany": "Filtrer par entreprise",
    "transactions.filterByCategory": "Filtrer par catégorie",
    "transactions.editTransaction": "Modifier la transaction",
    "transactions.deleteTransaction": "Supprimer la transaction",
    "transactions.close": "Fermer",
    "transactions.addCategory": "Ajouter la catégorie",
    "transactions.cancelAddCategory": "Annuler l'ajout de catégorie",
    "transactions.businessPurposePlaceholder": "Décrivez l'objectif commercial de cette transaction",
    "transactions.optional": "optionnel",
    "transactions.transferBetweenAccountsHint": "pour transfert entre comptes",
    "transactions.transferBetweenAccountsInfo": "Si un compte de destination est sélectionné, c'est un transfert entre comptes (aucune influence sur le portrait financier). Sinon, c'est un transfert entre personnes (sortie d'argent).",
    "transactions.fiscalInfo": "Informations fiscales",
    "transactions.taxableTransaction": "Transaction taxable (GST/QST applicable)",
    "transactions.receiptAvailable": "Reçu disponible",
    "transactions.businessPurpose": "Objectif commercial",
    "transactions.useManualTaxes": "Utiliser des montants de taxes manuels",
    "transactions.manualGst": "GST manuel",
    "transactions.manualQst": "QST manuel",
    "transactions.gstItc": "GST ITC",
    "transactions.qstItc": "QST ITC",
    "transactions.cancel": "Annuler",
    "transactions.save": "Enregistrer",
    "transactions.updateTransaction": "Mettre à jour la transaction",
    "transactions.noCompany": "Aucune entreprise",
    "transactions.noAccount": "Aucun compte",
    "transactions.errorAdd": "Erreur lors de l'ajout de la transaction. Vérifiez la console pour plus de détails.",
    "transactions.errorUpdate": "Erreur lors de la mise à jour de la transaction. Vérifiez la console pour plus de détails.",
    "transactions.errorDelete": "Erreur lors de la suppression de la transaction. Vérifiez la console pour plus de détails.",
    "transactions.errorDeleteDocument": "Erreur lors de la suppression du document.",
    "transactions.requiredFields": "Veuillez remplir tous les champs requis (montant et description).",
    "transactions.confirmDelete": "Êtes-vous sûr de vouloir supprimer cette transaction ?",
    "transactions.confirmDeleteDocument": "Êtes-vous sûr de vouloir supprimer ce document ?",
    
    // Budget
    "budget.title": "Budget",
    "budget.subtitle": "Gérez votre budget personnel",
    "budget.salary": "Salaire",
    "budget.salaryType": "Type de salaire",
    "budget.salaryAnnual": "Annuel",
    "budget.salaryBiweekly": "Aux deux semaines",
    "budget.fixedExpenses": "Dépenses fixes",
    "budget.variableExpenses": "Dépenses variables",
    "budget.addFixedExpense": "Ajouter une dépense fixe",
    "budget.addVariableExpense": "Ajouter une dépense variable",
    "budget.editVariableExpense": "Modifier une dépense variable",
    "budget.expenseWillBeAdded": "Cette dépense sera ajoutée comme transaction",
    "budget.mainInfo": "Informations principales",
    "budget.name": "Nom",
    "budget.amount": "Montant",
    "budget.startDate": "Date de début",
    "budget.endDate": "Date de fin",
    "budget.recurrence": "Récurrence",
    "budget.recurrenceNone": "Aucune",
    "budget.recurrenceWeekly": "Hebdomadaire",
    "budget.recurrenceBiweekly": "Aux deux semaines",
    "budget.recurrenceMonthly": "Mensuelle",
    "budget.recurrenceBimonthly": "Bimestrielle",
    "budget.recurrenceQuarterly": "Trimestrielle",
    "budget.recurrenceYearly": "Annuelle",
    "budget.delete": "Supprimer",
    "budget.edit": "Modifier",
    
    // Tax Filing
    "taxFiling.title": "Déclaration fiscale",
    "taxFiling.subtitle": "Gérez les déclarations fiscales du Canada et du Québec et les échéances.",
    "taxFiling.newFiling": "Nouvelle déclaration",
    "taxFiling.taxYear": "Année fiscale",
    "taxFiling.totalFilings": "Déclarations totales",
    "taxFiling.completed": "Terminées",
    "taxFiling.pending": "En attente",
    "taxFiling.totalTaxOwing": "Impôt total dû",
    "taxFiling.taxFilings": "Déclarations fiscales",
    "taxFiling.income": "Revenus",
    "taxFiling.expenses": "Dépenses",
    "taxFiling.netIncome": "Revenu net",
    "taxFiling.deadline": "Échéance",
    "taxFiling.taxOwing": "Impôt dû",
    "taxFiling.filed": "Déposé",
    "taxFiling.viewDetails": "Voir les détails",
    "taxFiling.importantDates": "Dates fiscales importantes",
    "taxFiling.federalProvincial": "Fédéral et Provincial",
    "taxFiling.federalOnly": "Fédéral uniquement",
    "taxFiling.createNewFiling": "Créer une nouvelle déclaration",
    "taxFiling.company": "Entreprise",
    "taxFiling.filingType": "Type de déclaration",
    "taxFiling.jurisdiction": "Juridiction",
    "taxFiling.totalIncome": "Revenus totaux",
    "taxFiling.totalExpenses": "Dépenses totales",
    "taxFiling.createFiling": "Créer la déclaration",
    
    // Reports
    "reports.title": "Rapports",
    "reports.subtitle": "Générez et gérez les rapports financiers.",
    "reports.generateReport": "Générer un rapport",
    "reports.templates": "Modèles de rapports",
    "reports.incomeStatement": "État des résultats",
    "reports.incomeStatementDesc": "Résumé des revenus et dépenses",
    "reports.balanceSheet": "Bilan",
    "reports.balanceSheetDesc": "Vue d'ensemble des actifs, passifs et capitaux propres",
    "reports.cashFlow": "Flux de trésorerie",
    "reports.cashFlowDesc": "Suivre les mouvements de trésorerie dans le temps",
    "reports.taxSummary": "Résumé fiscal",
    "reports.taxSummaryDesc": "Préparer la déclaration fiscale",
    "reports.expenseAnalysis": "Analyse des dépenses",
    "reports.expenseAnalysisDesc": "Répartition détaillée des dépenses",
    "reports.revenuForecast": "Prévision des revenus",
    "reports.revenuForecastDesc": "Projeter les revenus futurs",
    "reports.generate": "Générer",
    "reports.recentReports": "Rapports récents",
    "reports.reportName": "Nom du rapport",
    "reports.type": "Type",
    "reports.generated": "Généré",
    "reports.download": "Télécharger",
    "reports.scheduledReports": "Rapports programmés",
    "reports.scheduledDesc": "Générer automatiquement des rapports selon un calendrier.",
    "reports.scheduleReport": "Programmer un rapport",
    "reports.typeAnnual": "Rapport annuel",
    "reports.typeQuarterly": "Rapport trimestriel",
    "reports.typeMonthly": "Rapport mensuel",
  },
  en: {
    // Dashboard
    "dashboard.title": "Hello! 👋",
    "dashboard.subtitle": "Here's an overview of your financial situation today",
    "dashboard.revenu": "Total revenu (YTD)",
    "dashboard.expenses": "Total Expenses (YTD)",
    "dashboard.income": "Net Income (YTD)",
    "dashboard.margin": "Profit Margin",
    "dashboard.revenuVsExpenses": "revenu vs Expenses",
    "dashboard.expenseCategories": "Expense Categories",
    "dashboard.monthlyBreakdown": "Monthly Breakdown",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.viewAll": "View All",
    "dashboard.vsLastPeriod": "vs last period",
    "dashboard.date": "Date",
    "dashboard.description": "Description",
    "dashboard.category": "Category",
    "dashboard.type": "Type",
    "dashboard.amount": "Amount",
    "dashboard.incomeType": "Income",
    "dashboard.expenseType": "Expense",
    "dashboard.periodThisMonth": "This Month",
    "dashboard.periodThisQuarter": "This Quarter",
    "dashboard.periodYearToDate": "Year to Date",
    "dashboard.periodAllTime": "All Time",
    "dashboard.moreFilters": "More Filters",
    "dashboard.revenuLabel": "revenu",
    "dashboard.expensesLabel": "Expenses",
    
    // Dashboard - Months
    "dashboard.monthJan": "Jan",
    "dashboard.monthFeb": "Feb",
    "dashboard.monthMar": "Mar",
    "dashboard.monthApr": "Apr",
    "dashboard.monthMay": "May",
    "dashboard.monthJun": "Jun",
    "dashboard.monthJul": "Jul",
    "dashboard.monthAug": "Aug",
    "dashboard.monthSep": "Sep",
    "dashboard.monthOct": "Oct",
    "dashboard.monthNov": "Nov",
    "dashboard.monthDec": "Dec",
    
    // Dashboard - Expense Categories
    "dashboard.categorySalaries": "Salaries",
    "dashboard.categoryOfficeSupplies": "Office Supplies",
    "dashboard.categoryTravel": "Travel",
    "dashboard.categoryEquipment": "Equipment",
    "dashboard.categoryOther": "Other",
    
    // Dashboard - Transaction Categories
    "dashboard.transactionCategoryConsulting": "Consulting",
    "dashboard.transactionCategoryOfficeSupplies": "Office Supplies",
    "dashboard.transactionCategoryMealsEntertainment": "Meals & Entertainment",
    "dashboard.transactionCategorySoftware": "Software",
    
    // Dashboard - Transaction Descriptions
    "dashboard.transactionClientInvoice": "Client Invoice",
    "dashboard.transactionOfficeSupplies": "Office Supplies",
    "dashboard.transactionTeamLunch": "Team Lunch Meeting",
    "dashboard.transactionSoftwareLicense": "Software License",
    "dashboard.transactionFreelancePayment": "Freelance Payment",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and application preferences.",
    "settings.general": "General",
    "settings.account": "Account",
    "settings.notifications": "Notifications",
    "settings.billing": "Billing",
    "settings.language": "Language",
    "settings.languageDescription": "Choose the display language for the application",
    "settings.save": "Save Changes",
    
    // Sidebar
    "sidebar.dashboard": "Dashboard",
    "sidebar.companies": "Companies",
    "sidebar.transactions": "Transactions",
    "sidebar.accounting": "Accounting",
    "sidebar.taxFiling": "Tax Filing",
    "sidebar.reports": "Reports",
    "sidebar.anomalies": "Anomalies",
    "sidebar.assets": "Assets",
    "sidebar.settings": "Settings",
    "sidebar.brand": "NovaFinance",
    "sidebar.tagline": "Financial Management",
    "sidebar.footer": "© 2024 NovaFinance",
    "sidebar.footerTagline": "Accounting Made Simple ✨",
    "sidebar.personalDashboard": "Dashboard",
    "sidebar.personalTransactions": "Transactions",
    "sidebar.personalBudget": "Budget",
    "sidebar.personalAccounts": "Accounts",
    "sidebar.personalCards": "Cards",
    "sidebar.personalSavings": "Savings",
    "sidebar.personalReports": "Reports",
    "sidebar.personalSettings": "Settings",
    
    // Header
    "header.search": "Search transactions, companies...",
    "header.user": "User",
    "header.admin": "Admin",
    "header.logout": "Logout",
    "header.logoutSuccess": "Logout successful",
    "header.logoutSuccessDesc": "You have been successfully logged out.",
    "header.logoutError": "Error",
    "header.logoutErrorDesc": "An error occurred during logout.",
    "header.modeBusiness": "Business",
    "header.modePersonal": "Personal",
    "header.modeBusinessActive": "Business mode active",
    "header.modePersonalActive": "Personal finance mode active",
    "header.selectFiscalYear": "Select fiscal year",
    "header.changeMode": "Change mode",
    "header.goToSettings": "Go to settings",
    
    // Settings - General
    "settings.generalSettings": "General Settings",
    "settings.defaultCurrency": "Default Currency",
    "settings.fiscalYearStart": "Fiscal Year Start",
    "settings.theme": "Theme",
    "settings.themeLight": "Light",
    "settings.themeDark": "Dark",
    "settings.currencyCAD": "Canadian Dollar (CAD)",
    "settings.currencyUSD": "US Dollar (USD)",
    "settings.currencyEUR": "Euro (EUR)",
    "settings.monthJanuary": "January",
    "settings.monthApril": "April",
    "settings.monthJuly": "July",
    
    // Settings - Account
    "settings.accountSettings": "Account Settings",
    "settings.profilePhoto": "Profile Photo",
    "settings.uploadPhoto": "Upload Photo",
    "settings.changePhoto": "Change Photo",
    "settings.photoHint": "Accepted formats: JPG, PNG, GIF. Max size: 5MB",
    "settings.fullName": "Full Name",
    "settings.email": "Email",
    "settings.phone": "Phone",
    "settings.updateAccount": "Update Account",
    
    // Settings - Notifications
    "settings.notificationPreferences": "Notification Preferences",
    "settings.taxDeadlineReminders": "Tax Deadline Reminders",
    "settings.taxDeadlineDesc": "Get notified about upcoming tax deadlines",
    "settings.monthlyReports": "Monthly Reports",
    "settings.monthlyReportsDesc": "Receive monthly financial summaries",
    "settings.largeTransactions": "Large Transactions",
    "settings.largeTransactionsDesc": "Notify for transactions above $5,000",
    "settings.systemUpdates": "System Updates",
    "settings.systemUpdatesDesc": "Receive notifications about app updates",
    
    // Settings - Billing
    "settings.billingSubscription": "Billing & Subscription",
    "settings.currentPlan": "Current Plan",
    "settings.professional": "Professional",
    "settings.paymentMethod": "Payment Method",
    "settings.edit": "Edit",
    
    // Settings - Security
    "settings.security": "Security",
    "settings.changePassword": "Change Password",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmPassword": "Confirm Password",
    "settings.updatePassword": "Update Password",
    "settings.twoFactorAuth": "Two-Factor Authentication",
    "settings.twoFactorDesc": "Add an extra layer of security to your account.",
    "settings.enable2FA": "Enable 2FA",
    
    // NotFound
    "notFound.title": "Page Not Found",
    "notFound.message": "Sorry, we couldn't find the page you're looking for. Let's get you back on track.",
    "notFound.backToDashboard": "Back to Dashboard",
    
    // Companies
    "companies.title": "Companies",
    "companies.subtitle": "Manage your business profiles and tax information.",
    "companies.addCompany": "Add Company",
    "companies.businessNumber": "Business Number",
    "companies.neq": "NEQ",
    "companies.taxNumber": "Tax Number",
    "companies.owner": "Owner",
    "companies.contactEmail": "Contact Email",
    "companies.integrations": "Integrations",
    "companies.stripeConnected": "✓ Stripe Connected",
    "companies.stripe": "Stripe",
    "companies.ytdrevenu": "YTD revenu",
    "companies.addNewCompany": "Add New Company",
    "companies.companyName": "Company Name",
    "companies.companyNamePlaceholder": "Enter company name",
    "companies.legalName": "Legal Name",
    "companies.legalNamePlaceholder": "Enter legal business name",
    "companies.businessNumberPlaceholder": "123-456-789",
    "companies.neqPlaceholder": "1234 5678 90",
    "companies.cancel": "Cancel",
    "companies.createCompany": "Create Company",
    "companies.moreOptions": "More options",
    "companies.editCompany": "Edit company",
    "companies.deleteCompany": "Delete company",
    
    // Transactions
    "transactions.title": "Expenses & Income",
    "transactions.subtitle": "Track and manage all financial transactions.",
    "transactions.addTransaction": "Add Transaction",
    "transactions.totalIncome": "Total Income",
    "transactions.totalExpenses": "Total Expenses",
    "transactions.net": "Net",
    "transactions.searchPlaceholder": "Search transactions...",
    "transactions.allTransactions": "All Transactions",
    "transactions.incomeOnly": "Income Only",
    "transactions.expensesOnly": "Expenses Only",
    "transactions.export": "Export",
    "transactions.print": "Print",
    "transactions.company": "Company",
    "transactions.tags": "Tags",
    "transactions.actions": "Actions",
    "transactions.addTransactionTitle": "Add Transaction",
    "transactions.type": "Type",
    "transactions.description": "Description",
    "transactions.descriptionPlaceholder": "Enter description",
    "transactions.amount": "Amount",
    "transactions.amountPlaceholder": "0.00",
    "transactions.category": "Category",
    "transactions.date": "Date",
    "transactions.income": "Income",
    "transactions.expense": "Expense",
    "transactions.addCustomCategory": "Add custom category",
    "transactions.customCategoryPlaceholder": "Category name",
    "transactions.categoryUtilities": "Utilities",
    "transactions.account": "Account",
    "transactions.accountTo": "Destination account",
    "transactions.transferType": "Transfer type",
    "transactions.transferBetweenAccounts": "Transfer between accounts",
    "transactions.transferBetweenPersons": "Transfer between persons",
    "transactions.typerevenu": "revenu",
    "transactions.typeDepense": "Expense",
    "transactions.typeTransfert": "Transfer",
    "transactions.typeRemboursement": "Reimbursement",
    "transactions.typePaiementFacture": "Bill payment",
    "transactions.allAccounts": "All accounts",
    "transactions.allCompanies": "All companies",
    "transactions.allIncomeExpenses": "All (Income + Expenses)",
    "transactions.filterByType": "Filter by transaction type",
    "transactions.filterByDate": "Filter by date",
    "transactions.filterByAccount": "Filter by account",
    "transactions.filterByCompany": "Filter by company",
    "transactions.filterByCategory": "Filter by category",
    "transactions.editTransaction": "Edit transaction",
    "transactions.deleteTransaction": "Delete transaction",
    "transactions.close": "Close",
    "transactions.addCategory": "Add category",
    "transactions.cancelAddCategory": "Cancel adding category",
    "transactions.businessPurposePlaceholder": "Describe the business purpose of this transaction",
    "transactions.optional": "optional",
    "transactions.transferBetweenAccountsHint": "for transfer between accounts",
    "transactions.transferBetweenAccountsInfo": "If a destination account is selected, it's a transfer between accounts (no impact on financial portrait). Otherwise, it's a transfer between persons (money outflow).",
    "transactions.fiscalInfo": "Tax information",
    "transactions.taxableTransaction": "Taxable transaction (GST/QST applicable)",
    "transactions.receiptAvailable": "Receipt available",
    "transactions.businessPurpose": "Business purpose",
    "transactions.useManualTaxes": "Use manual tax amounts",
    "transactions.manualGst": "Manual GST",
    "transactions.manualQst": "Manual QST",
    "transactions.gstItc": "GST ITC",
    "transactions.qstItc": "QST ITC",
    "transactions.cancel": "Cancel",
    "transactions.save": "Save",
    "transactions.updateTransaction": "Update transaction",
    "transactions.noCompany": "No company",
    "transactions.noAccount": "No account",
    "transactions.errorAdd": "Error adding transaction. Check the console for more details.",
    "transactions.errorUpdate": "Error updating transaction. Check the console for more details.",
    "transactions.errorDelete": "Error deleting transaction. Check the console for more details.",
    "transactions.errorDeleteDocument": "Error deleting document.",
    "transactions.requiredFields": "Please fill in all required fields (amount and description).",
    "transactions.confirmDelete": "Are you sure you want to delete this transaction?",
    "transactions.confirmDeleteDocument": "Are you sure you want to delete this document?",
    
    // Budget
    "budget.title": "Budget",
    "budget.subtitle": "Manage your personal budget",
    "budget.salary": "Salary",
    "budget.salaryType": "Salary type",
    "budget.salaryAnnual": "Annual",
    "budget.salaryBiweekly": "Biweekly",
    "budget.fixedExpenses": "Fixed expenses",
    "budget.variableExpenses": "Variable expenses",
    "budget.addFixedExpense": "Add fixed expense",
    "budget.addVariableExpense": "Add variable expense",
    "budget.editVariableExpense": "Edit variable expense",
    "budget.expenseWillBeAdded": "This expense will be added as a transaction",
    "budget.mainInfo": "Main information",
    "budget.name": "Name",
    "budget.amount": "Amount",
    "budget.startDate": "Start date",
    "budget.endDate": "End date",
    "budget.recurrence": "Recurrence",
    "budget.recurrenceNone": "None",
    "budget.recurrenceWeekly": "Weekly",
    "budget.recurrenceBiweekly": "Biweekly",
    "budget.recurrenceMonthly": "Monthly",
    "budget.recurrenceBimonthly": "Bimonthly",
    "budget.recurrenceQuarterly": "Quarterly",
    "budget.recurrenceYearly": "Yearly",
    "budget.delete": "Delete",
    "budget.edit": "Edit",
    
    // Tax Filing
    "taxFiling.title": "Tax Filing",
    "taxFiling.subtitle": "Manage Canada and Quebec tax filings and deadlines.",
    "taxFiling.newFiling": "New Filing",
    "taxFiling.taxYear": "Tax Year",
    "taxFiling.totalFilings": "Total Filings",
    "taxFiling.completed": "Completed",
    "taxFiling.pending": "Pending",
    "taxFiling.totalTaxOwing": "Total Tax Owing",
    "taxFiling.taxFilings": "Tax Filings",
    "taxFiling.income": "Income",
    "taxFiling.expenses": "Expenses",
    "taxFiling.netIncome": "Net Income",
    "taxFiling.deadline": "Deadline",
    "taxFiling.taxOwing": "Tax Owing",
    "taxFiling.filed": "Filed",
    "taxFiling.viewDetails": "View Details",
    "taxFiling.importantDates": "Important Tax Dates",
    "taxFiling.federalProvincial": "Federal & Provincial",
    "taxFiling.federalOnly": "Federal Only",
    "taxFiling.createNewFiling": "Create New Tax Filing",
    "taxFiling.company": "Company",
    "taxFiling.filingType": "Filing Type",
    "taxFiling.jurisdiction": "Jurisdiction",
    "taxFiling.totalIncome": "Total Income",
    "taxFiling.totalExpenses": "Total Expenses",
    "taxFiling.createFiling": "Create Filing",
    
    // Reports
    "reports.title": "Reports",
    "reports.subtitle": "Generate and manage financial reports.",
    "reports.generateReport": "Generate Report",
    "reports.templates": "Report Templates",
    "reports.incomeStatement": "Income Statement",
    "reports.incomeStatementDesc": "Summary of revenus and expenses",
    "reports.balanceSheet": "Balance Sheet",
    "reports.balanceSheetDesc": "Assets, liabilities, and equity overview",
    "reports.cashFlow": "Cash Flow",
    "reports.cashFlowDesc": "Track cash movement over time",
    "reports.taxSummary": "Tax Summary",
    "reports.taxSummaryDesc": "Prepare for tax filing",
    "reports.expenseAnalysis": "Expense Analysis",
    "reports.expenseAnalysisDesc": "Detailed expense breakdown",
    "reports.revenuForecast": "revenu Forecast",
    "reports.revenuForecastDesc": "Project future revenus",
    "reports.generate": "Generate",
    "reports.recentReports": "Recent Reports",
    "reports.reportName": "Report Name",
    "reports.type": "Type",
    "reports.generated": "Generated",
    "reports.download": "Download",
    "reports.scheduledReports": "Scheduled Reports",
    "reports.scheduledDesc": "Automatically generate reports on a schedule.",
    "reports.scheduleReport": "Schedule Report",
    "reports.typeAnnual": "Annual Report",
    "reports.typeQuarterly": "Quarterly Report",
    "reports.typeMonthly": "Monthly Report",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language;
    return saved || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations.fr];
    if (translation) {
      return translation;
    }
    // Si la traduction n'existe pas, essayer de formater la clé de manière lisible
    // au lieu d'afficher "dashboard.monthAug", afficher "Août" par exemple
    if (key.includes("month")) {
      const monthMap: { [key: string]: string } = {
        "monthJan": language === "fr" ? "Jan" : "Jan",
        "monthFeb": language === "fr" ? "Fév" : "Feb",
        "monthMar": language === "fr" ? "Mar" : "Mar",
        "monthApr": language === "fr" ? "Avr" : "Apr",
        "monthMay": language === "fr" ? "Mai" : "May",
        "monthJun": language === "fr" ? "Jun" : "Jun",
        "monthJul": language === "fr" ? "Jul" : "Jul",
        "monthAug": language === "fr" ? "Aoû" : "Aug",
        "monthSep": language === "fr" ? "Sep" : "Sep",
        "monthOct": language === "fr" ? "Oct" : "Oct",
        "monthNov": language === "fr" ? "Nov" : "Nov",
        "monthDec": language === "fr" ? "Déc" : "Dec",
      };
      const monthKey = key.split(".").pop() || "";
      if (monthMap[monthKey]) {
        return monthMap[monthKey];
      }
    }
    // Pour les autres clés manquantes, retourner un message d'erreur en mode dev, ou la clé formatée
    if (import.meta.env.DEV) {
      console.warn(`Traduction manquante pour la clé: ${key}`);
    }
    // Retourner la dernière partie de la clé (après le dernier point) formatée
    const lastPart = key.split(".").pop() || key;
    return lastPart.charAt(0).toUpperCase() + lastPart.slice(1).replace(/([A-Z])/g, " $1");
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

